name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          pytest
          coverage report

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build Backend Container
        run: |
          podman build -t mental-health-backend:${{ github.sha }} -f infrastructure/scripts/Dockerfile .
          podman tag mental-health-backend:${{ github.sha }} mental-health-backend:latest
      
      - name: Build Frontend Container
        run: |
          cd frontend/chainlit
          chainlit build --host 0.0.0.0 --port 8501
          podman build -t mental-health-frontend:${{ github.sha }} -f ../../infrastructure/scripts/Dockerfile .
          podman tag mental-health-frontend:${{ github.sha }} mental-health-frontend:latest
      
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Push Backend Image
        run: |
          podman push mental-health-backend:latest ${{ secrets.REGISTRY_URL }}/mental-health-backend:latest
          podman push mental-health-backend:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/mental-health-backend:${{ github.sha }}
      
      - name: Push Frontend Image
        run: |
          podman push mental-health-frontend:latest ${{ secrets.REGISTRY_URL }}/mental-health-frontend:latest
          podman push mental-health-frontend:${{ github.sha }} ${{ secrets.REGISTRY_URL }}/mental-health-frontend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Backend to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name mental-health-backend \
            --image ${{ secrets.REGISTRY_URL }}/mental-health-backend:latest \
            --cpu 1 \
            --memory 1.5 \
            --ports 8000 \
            --environment-variables \
              COSMOS_CONNECTION_STRING="${{ secrets.COSMOS_CONNECTION_STRING }}" \
              FIREBASE_CONFIG="${{ secrets.FIREBASE_CONFIG }}" \
              PRIMARY_MODEL="${{ secrets.PRIMARY_MODEL }}" \
              SENTIMENT_MODEL="${{ secrets.SENTIMENT_MODEL }}"
      
      - name: Deploy Frontend to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name mental-health-frontend \
            --image ${{ secrets.REGISTRY_URL }}/mental-health-frontend:latest \
            --cpu 1 \
            --memory 1.5 \
            --ports 8501